server:
  port: 8675
ex:
  application:
    name: message-box-core
  datasource:
    ip: 192.168.67.100
    port: 3306
    name: ex
    username: root
    password: database@2021
  thread-pool:
    message-push-size: 10
